### ISSUE TITLE
DOM: Event Listener

### ISSUE THREAD

**Issue by reacto11mecha** [bellshade/Javascript#153]
## Nama Materi
DOM: Event Listener

## Deskripsi
Folder: `/learn/DOM/006_Event_Listener`

**Comment by reacto11mecha** [comment]
@hasheemi komentar disini om biar bisa di assign ke om

**Comment by hasheemi** [comment]
Ok kak @reacto11mecha , segera dilaksanakan

**Comment by azqilana** [comment]
om @reacto11mecha  bisa tolong asigned issue ini buat om @hasheemi dia mau kerjain kan katanya  td saya tanya dia jadi ambil atau ngga dia bilang jd ambil niatnya tadi saya mau ambil tapi karena om @hasheemi udah mau erjain katanya jd nggak jd

**Comment by reacto11mecha** [comment]
> om @reacto11mecha bisa tolong asigned issue ini buat om @hasheemi dia mau kerjain kan katanya td saya tanya dia jadi ambil atau ngga dia bilang jd ambil niatnya tadi saya mau ambil tapi karena om @hasheemi udah mau kerjain katanya jd nggak jd saya ambil

Oiya, sori sori waktu kemaren di aplikasi androidnya ke assign, om @hasheemi maaf ya om, kerjain aja ya sesuai materinya 🙏
