### ISSUE TITLE
DOM: Event Bubbling and Capturing

### ISSUE THREAD

**Issue by reacto11mecha** [bellshade/Javascript#154]
## Nama Materi
DOM: Event Bubbling and Capturing

## Deskripsi
Folder: `/learn/DOM/007_Event_Bubbling_and_Capturing`

**Comment by azqilana** [comment]
om @reacto11mecha saya ambil materi in ya lusa saya kerjain insya aalah besok selesai tugassaya om

**Comment by reacto11mecha** [comment]
Sip, ku assign ya

**Comment by azqilana** [comment]
terima kasih 

> Sip, ku assign ya
terima kasih
