### ISSUE TITLE
List Materi DOM Javascript

### ISSUE THREAD

**Issue by reacto11mecha** [bellshade/Javascript#155]
Daftar-Daftar materi yang sudah diselesaikan untuk materi DOM Javascript. 

> Jika `open` berarti belum dikerjakan, kalau `close` berarti sudah selesai.

- [x] #147
- [x] #148
- [x] #149 
- [x] #151 
- [x] #152 
- [x] #153  
- [x] #156 
- [x] #154 

Jika ingin menambahkan materi ini, di ingatkan kembali bacalah [Panduan Kontribusi](https://github.com/bellshade/Javascript/blob/main/CONTRIBUTING.md) atau panduan lanjutan #58. Untuk materi ini diperlukan minimal 3 file jika ingin menambahkan foldernya, yaitu file `html`, `js`, dan `md` sebagai penjelasannya. Untuk folder sudah dijelaskan dimasing masing issue. Balas di issue yang ingin dikerjakan dengan `saya ingin mengerjakan` atau selain itu.

Jika ada masalah silahkan di diskusikan di issue ini atau di [discord wpu](https://discord.gg/wpu).
Jika dirasa materi kurang, [tambahkan issue untuk materi baru](https://github.com/bellshade/Javascript/issues/new?assignees=&labels=learn&template=new-learn.md&title=)

Happy Contributing :tada:

**Comment by reacto11mecha** [comment]
> > Daftar-Daftar materi yang sudah diselesaikan untuk materi DOM Javascript.
> > > Jika `open` berarti belum dikerjakan, kalau `close` berarti sudah selesai.
> > 
> > 
> > 
> > * [x]   [DOM: Pengenalan #147](https://github.com/bellshade/Javascript/issues/147)
> > * [ ]   [DOM: Nodes #148](https://github.com/bellshade/Javascript/issues/148)
> > * [ ]   [DOM: Collections #149](https://github.com/bellshade/Javascript/issues/149)
> > * [ ]   [DOM: Methods #151](https://github.com/bellshade/Javascript/issues/151)
> > * [ ]   [DOM: Events #152](https://github.com/bellshade/Javascript/issues/152)
> > * [ ]   [DOM: Event Listener #153](https://github.com/bellshade/Javascript/issues/153)
> > * [ ]   [DOM: Event Bubbling and Capturing #154](https://github.com/bellshade/Javascript/issues/154)
> > 
> > Jika ingin menambahkan materi ini, di ingatkan kembali bacalah [Panduan Kontribusi](https://github.com/bellshade/Javascript/blob/main/CONTRIBUTING.md) atau panduan lanjutan #58. Untuk materi ini diperlukan minimal 3 file jika ingin menambahkan foldernya, yaitu file `html`, `js`, dan `md` sebagai penjelasannya. Untuk folder sudah dijelaskan dimasing masing issue. Balas di issue yang ingin dikerjakan dengan `saya ingin mengerjakan` atau selain itu.
> > Jika ada masalah silahkan di diskusikan di issue ini atau di [discord wpu](https://discord.gg/wpu). Jika dirasa materi kurang, [tambahkan issue untuk materi baru](https://github.com/bellshade/Javascript/issues/new?assignees=&labels=learn&template=new-learn.md&title=)
> > Happy Contributing 🎉
> 
> saya ingin mengejakan dom collection

Komentar di issuenya, biar bisa di assign

**Comment by hasheemi** [comment]
> Daftar-Daftar materi yang sudah diselesaikan untuk materi DOM Javascript.
> 
> > Jika `open` berarti belum dikerjakan, kalau `close` berarti sudah selesai.
> 
> * [x]  [DOM: Pengenalan #147](https://github.com/bellshade/Javascript/issues/147)
> * [x]  [DOM: Nodes #148](https://github.com/bellshade/Javascript/issues/148)
> * [x]  [DOM: Collections #149](https://github.com/bellshade/Javascript/issues/149)
> * [ ]  [DOM: Methods #151](https://github.com/bellshade/Javascript/issues/151)
> * [x]  [DOM: Events #152](https://github.com/bellshade/Javascript/issues/152)
> * [ ]  [DOM: Event Listener #153](https://github.com/bellshade/Javascript/issues/153)
> * [ ]  [DOM: Event Bubbling and Capturing #154](https://github.com/bellshade/Javascript/issues/154)
> * [x]  [DOM: Traversal  #156](https://github.com/bellshade/Javascript/issues/156)
> 
> Jika ingin menambahkan materi ini, di ingatkan kembali bacalah [Panduan Kontribusi](https://github.com/bellshade/Javascript/blob/main/CONTRIBUTING.md) atau panduan lanjutan #58. Untuk materi ini diperlukan minimal 3 file jika ingin menambahkan foldernya, yaitu file `html`, `js`, dan `md` sebagai penjelasannya. Untuk folder sudah dijelaskan dimasing masing issue. Balas di issue yang ingin dikerjakan dengan `saya ingin mengerjakan` atau selain itu.
> 
> Jika ada masalah silahkan di diskusikan di issue ini atau di [discord wpu](https://discord.gg/wpu). Jika dirasa materi kurang, [tambahkan issue untuk materi baru](https://github.com/bellshade/Javascript/issues/new?assignees=&labels=learn&template=new-learn.md&title=)
> 
> Happy Contributing 🎉
Bang saya pengen ambil yang dom methods , insya Allah Ahas atau Senin , terimakasih

**Comment by reacto11mecha** [comment]
> > Daftar-Daftar materi yang sudah diselesaikan untuk materi DOM Javascript.
> > > Jika `open` berarti belum dikerjakan, kalau `close` berarti sudah selesai.
> > 
> > 
> > 
> > * [x]   [DOM: Pengenalan #147](https://github.com/bellshade/Javascript/issues/147)
> > * [x]   [DOM: Nodes #148](https://github.com/bellshade/Javascript/issues/148)
> > * [x]   [DOM: Collections #149](https://github.com/bellshade/Javascript/issues/149)
> > * [ ]   [DOM: Methods #151](https://github.com/bellshade/Javascript/issues/151)
> > * [x]   [DOM: Events #152](https://github.com/bellshade/Javascript/issues/152)
> > * [ ]   [DOM: Event Listener #153](https://github.com/bellshade/Javascript/issues/153)
> > * [ ]   [DOM: Event Bubbling and Capturing #154](https://github.com/bellshade/Javascript/issues/154)
> > * [x]   [DOM: Traversal  #156](https://github.com/bellshade/Javascript/issues/156)
> > 
> > Jika ingin menambahkan materi ini, di ingatkan kembali bacalah [Panduan Kontribusi](https://github.com/bellshade/Javascript/blob/main/CONTRIBUTING.md) atau panduan lanjutan #58. Untuk materi ini diperlukan minimal 3 file jika ingin menambahkan foldernya, yaitu file `html`, `js`, dan `md` sebagai penjelasannya. Untuk folder sudah dijelaskan dimasing masing issue. Balas di issue yang ingin dikerjakan dengan `saya ingin mengerjakan` atau selain itu.
> > Jika ada masalah silahkan di diskusikan di issue ini atau di [discord wpu](https://discord.gg/wpu). Jika dirasa materi kurang, [tambahkan issue untuk materi baru](https://github.com/bellshade/Javascript/issues/new?assignees=&labels=learn&template=new-learn.md&title=)
> > Happy Contributing 🎉
> > Bang saya pengen ambil yang dom methods , insya Allah Ahas atau Senin , terimakasih

Bukannya yang #151 itu dah sama om @azqilana ?

**Comment by reacto11mecha** [comment]
Kalo udah ada assignees jan diambil om, berarti ambilnya yang laen

**Comment by hasheemi** [comment]
Oh sudah ta , saya tak pindah

**Comment by reacto11mecha** [comment]
> Oh sudah ta , saya tak pindah

Sekalian om komentar di issuenya biar di assign ke om, biar yang lain juga tau ini siapa yang udah kerjain

**Comment by hasheemi** [comment]
Saya mau ambil dom event listener

**Comment by azqilana** [comment]
> Saya mau ambil dom event listener

lanjutkan gas om event Listenernya

**Comment by reacto11mecha** [comment]
Close karena materi di anggap sudah selesai, jika ada tambahan materi silahkan berkomentar saja di issue ini.
