### ISSUE TITLE
Menambahkan cara setup ui-server

### ISSUE THREAD

**Issue by reacto11mecha** [bellshade/Javascript#215]
Karena di repo js ini sudah ada ui server (#171) tetapi belum ada penjelasannya, oleh karena itu diperlukan cara penggunaan ui server di readme root

Patokan readme kira kira bisa seperti ini
https://github.com/bellshade/PHP#panduan-penggunaan

**Comment by hasheemi** [comment]
sudah dikerjakan di pr #308
