### ISSUE TITLE
Functional Programming

### ISSUE THREAD

**Issue by Fakhri1999** [bellshade/Javascript#269]
## Nama Materi
Functional Programming

## Deskripsi
Materi OOP sudah ada, dan saya pikir perlu untuk menambahkan materi FP dikarenakan JS bisa digunakan dengan OOP ataupun FP.

## Saran List Materi
- First-Class Objects
- Pure Functions
- Higher-Order Functions
- Composition
- Immutability

Saya ingin mengerjakan materi ini

**Comment by reacto11mecha** [comment]
> ## Nama Materi
> Functional Programming
> 
> ## Deskripsi
> Materi OOP sudah ada, dan saya pikir perlu untuk menambahkan materi FP dikarenakan JS bisa digunakan dengan OOP ataupun FP.
> 
> ## Saran List Materi
> * First-Class Objects
> * Pure Functions
> * Higher-Order Functions
> * Composition
> * Immutability
> 
> Saya ingin mengerjakan materi ini

Sebelumnya makasih buat sarannya, untuk penempatan folder mau ditaro di sebelah mana ya ?

**Comment by Fakhri1999** [comment]
di folder `learn`, sejajar sama `OOP`

**Comment by reacto11mecha** [comment]
Materinya mau satu file aja atau berderet kayak materi gitu ? Ada roadmap materinya ?

**Comment by Fakhri1999** [comment]
> Materinya mau satu file aja atau berderet kayak materi gitu ? 

tiap materi ada filenya sendiri2 gitu. 

> Ada semacem versi artikel dari materinya ?

maksudnya gmna? nanti untuk sumber tiap materinya, aku ambil dri bbrp sumber trus aku olah jadi 1 kesatuan

**Comment by reacto11mecha** [comment]
> > Materinya mau satu file aja atau berderet kayak materi gitu ?
> 
> tiap materi ada filenya sendiri2 gitu.

Maksudnya semisal begini, first class object itu folder sendiri, Pure Function itu folder sendiri gitu kayak folder OOP dengan materi yang kecil kecilnya

> > Ada semacem versi artikel dari materinya ?
> 
> maksudnya gmna? nanti untuk sumber tiap materinya, aku ambil dri bbrp sumber trus aku olah jadi 1 kesatuan

Ohh ya udah gapapa

**Comment by Fakhri1999** [comment]
> Maksudnya semisal begini, first class object itu folder sendiri, Pure Function itu folder sendiri gitu kayak folder OOP dengan materi yang kecil kecilnya

oalah, iya tiap sub materinya jadi folder sendiri
