### ISSUE TITLE
Materi pembelajaran memiliki kesalahan pada contoh code

### ISSUE THREAD

**Issue by manh21** [bellshade/Javascript#280]
## Deskripsi
Bug ini terdapat pada https://github.com/bellshade/Javascript/blob/308b7135e9df73ec2df339fae4fdaa2ab65a5780/learn/ES6/012_string_includes/stringIncludes.js#L1-L5 

Seharunya menghasilkan output: `false`

## Saran kamu
Memberikan perbaikan typo atau merubah output menjadi false

**Comment by reacto11mecha** [comment]
Kayaknya materi yang ini bisa dihapus sih, soalnya penjelasan yang lebih lengkap udah ada di folder `String Helpers` materi materinya
