### ISSUE TITLE
Menggunakan best practice pada arrow function

### ISSUE THREAD

**Issue by manh21** [bellshade/Javascript#281]
## Deskripsi
Contoh arrow function tidak menggunakan best pratice. 
Apabila hanya terdapat satu variabel saja tidak menggunakan kurung buka `(` dan kurung tutup `)`
https://github.com/bellshade/Javascript/blob/308b7135e9df73ec2df339fae4fdaa2ab65a5780/learn/ES6/003_arrow_function/arrowFunction.js#L5
Seharusnya menjadi
```js
console.log(islands.map(island => island.length)); // [8, 4, 10, 8 , 5] 
```

## Saran kamu
Merubah contoh arrow function sesuai dengan best practice yang ada
Referensi:
* https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions

**Comment by reacto11mecha** [comment]
Hmm, terimakasih udah kasih saran sebelumnya

Untuk masalah ini berarti nanti bisa di ubah konfigurasi prettiernya, jadi di bikin avoid si `arrowParens` nya
https://prettier.io/docs/en/options.html#arrow-function-parentheses

**Comment by reacto11mecha** [comment]
Nganu om @manh21, itu pas di coba kena codacy, di repo ini dia musti dipakein tanda kurung buat pembungkus parameternya, di coba kemaren sampe 100 issue katanya.

Commit: https://github.com/bellshade/Javascript/pull/284/commits/434a448cb80a7590f5544c2f1659200f6db1d993
Issue Codacy (Sekarang udah fix, jadi udah normal lagi): https://github.com/bellshade/Javascript/runs/5259390889

**Comment by reacto11mecha** [comment]
Untuk kelanjutan issue ini mau gimana @manh21 ? Kemungkinannya di close tanpa fix sama sekali
