### ISSUE TITLE
Algoritma Quicksort

### ISSUE THREAD

**Issue by ibrahim4529** [bellshade/Javascript#50]
## Nama Algoritma
Quicksort
## Deskripsi
Quicksort merupakan Algoritme Pembagi. Pertama quicksort membagi list yang besar menjadi dua buah sub list yang lebih kecil: element kecil dan element besar. Quicksort kemudian dapat menyortir sub list itu secara rekursif.
https://id.wikipedia.org/wiki/Quicksort

**Comment by AlfatArdiansa** [comment]
Mau sekalian sama sorting algorithm yang lain gk?
biar sekali buat gitu

**Comment by ibrahim4529** [comment]
Kayaknya udah ada beberapa implementasi di folder sorting_algorithm, saya mungkin cuma mau implement ini aja dulu mas.

**Comment by AlfatArdiansa** [comment]
Udah ada yang ngehandle issue ini? atau belom?

**Comment by ibrahim4529** [comment]
belom kayaknya

**Comment by reacto11mecha** [comment]
Udah ada yang handle issuenya belum ? Kalo mau buat sendiri, assign di issuenya sekalian link di pull requestnya buat close issue ini.

**Comment by AlfatArdiansa** [comment]
Yaudah saya ambil aja

**Comment by AlfatArdiansa** [comment]
![gambar](https://user-images.githubusercontent.com/53366314/135752371-16574b4b-9436-497c-9353-266f62df9d9d.png)
Sial kena Stackoverflow :(
