### ISSUE TITLE
QUESTION : directori untuk NodeJS dimana??

### ISSUE THREAD

**Issue by jefripunza** [bellshade/Javascript#75]
apakah disatukan kedalam folder yang sudah ada?

### saran : buat folder baru "NodeJS"

**Comment by wanrabbae** [comment]
Boleh ajh, tapi mau buat apa dulu nih ?

**Comment by mzaini30** [comment]
> apakah disatukan kedalam folder yang sudah ada?
> 
> ### saran : buat folder baru "NodeJS"

Maksudnya? Kan repo ini bisa pakai NodeJS. Tinggal jalankan aja `npm install`.

**Comment by jefripunza** [comment]
Ya kan ada juga ya yg kesini mau cari cara singkat misal nih,, mau mempercantik CLI di NodeJS atau apapun lah trik2 yg out of the box,, mumpung aku punya banyak cara ini pengen tau tak push disini biar nggak lupa juga 😂

**Comment by jefripunza** [comment]
Mungkin ada juga yg pointer nya cuman sekedar javascript untuk web doank, nah gimana yg keliling mau liat NodeJS kalo aku pribadi keliling di folder javascript implementasi nya cuman di js web doank,, kasian donk makhluk NodeJS nya 😂

**Comment by reacto11mecha** [comment]
> Ya kan ada juga ya yg kesini mau cari cara singkat misal nih,, mau mempercantik CLI di NodeJS atau apapun lah trik2 yg out of the box,, mumpung aku punya banyak cara ini pengen tau tak push disini biar nggak lupa juga 😂

Kalo cli mesti library kan ? Kalo perlu module kita belum terima dulu karena kita masih terfokus implemen sesuatu tanpa library. Bisa aja ditambahin cuman di pentingkan dulu implementasinya dalam versi native

**Comment by jefripunza** [comment]
oh gitu ya,, oke deh,, ma'acih,, yaudah tak isi dulu yg native2 nya

**Comment by reacto11mecha** [comment]
Nama foldernya `node_js` kalo mau nambahin

**Comment by jefripunza** [comment]
boleh2,
kami segenap pengguna nodejs merasa terbantu :V
